apply plugin: 'application'


java.sourceCompatibility = 17
java.targetCompatibility = 17
if (JavaVersion.current().isJava9Compatible()) {
        compileJava.options.release.set(17)
}

mainClassName = 'io.github.uoyteamsix.headless.HeadlessLauncher'
application.setMainClass(mainClassName)
eclipse.project.name = appName + '-headless'

dependencies {
  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
  implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
  implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
  implementation project(':core')
}

dependencies {
  api("com.badlogicgames.gdx:gdx:1.12.1")
  api("com.badlogicgames.gdx:gdx-freetype:1.12.1")
  implementation("com.badlogicgames.gdx:gdx-backend-lwjgl3:1.12.1")
  implementation("com.badlogicgames.gdx:gdx-platform:1.12.1:natives-desktop")
  implementation("com.badlogicgames.gdx:gdx-freetype-platform:1.12.1:natives-desktop")
  testImplementation(platform("org.junit:junit-bom:5.10.0"))
  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

dependencies {
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
  testImplementation 'org.mockito:mockito-core:4.2.0'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}

jar {
  archiveBaseName.set(appName)
  duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
  dependsOn configurations.runtimeClasspath
  from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
  manifest {
    attributes 'Main-Class': project.mainClassName
  }
  doLast {
    file(archiveFile).setExecutable(true, false)
  }
}

// Equivalent to the jar task; here for compatibility with gdx-setup.
tasks.register('dist') {
  dependsOn 'jar'
}
