
plugins {
  id 'checkstyle'
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'
sourceSets.test.resources.srcDirs += [ rootProject.file('assets').path ]

def checkstyleVersion = '10.21.0'

configurations {
  checkstyleRules
}

dependencies {
  checkstyleRules(
          "com.puppycrawl.tools:checkstyle:${checkstyleVersion}") {
    transitive = false
  }
}

checkstyle {
  toolVersion "${checkstyleVersion}"
  config = resources.text.fromArchiveEntry(
    configurations.checkstyleRules, 'google_checks.xml')
}

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

dependencies {
  api("com.badlogicgames.gdx:gdx:1.12.1")
  api("com.badlogicgames.gdx:gdx-freetype:1.12.1")
  implementation("com.badlogicgames.gdx:gdx-backend-lwjgl3:1.12.1")
  implementation("com.badlogicgames.gdx:gdx-platform:1.12.1:natives-desktop")
  implementation("com.badlogicgames.gdx:gdx-freetype-platform:1.12.1:natives-desktop")
  testImplementation(platform("org.junit:junit-bom:5.10.0"))
  testImplementation("org.junit.jupiter:junit-jupiter")
}

dependencies {
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
  testImplementation 'org.mockito:mockito-core:4.2.0'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}

jar {
  archiveBaseName= 'lib'
  destinationDirectory = file("core/build/libs")
}
